INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME, BIRTHDATE) VALUES (1, 'Joe', 'Dalton', '1970-01-02');
INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME, BIRTHDATE) VALUES (2, 'Jack', 'Dalton', '1973-04-05');
INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME, BIRTHDATE) VALUES (3, 'William', 'Dalton', '1976-07-08');
INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME, BIRTHDATE) VALUES (4, 'Averell', 'Dalton', '1979-10-11');
INSERT INTO PERSON(ID, FIRST_NAME, LAST_NAME)            VALUES (5, 'Ma', 'Dalton');